[build]
builder = "nixpacks"

[deploy]
startCommand = "echo \"$GCS_KEY_B64\" | base64 -d > /app/gcs-key.json && sleep 2 && node server/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services.backend]
source = "."
build.builder = "nixpacks"
deploy.startCommand = "echo \"$GCS_KEY_B64\" | base64 -d > /app/gcs-key.json && sleep 2 && node server/index.js"
