import React from 'react';
import { DownloadIcon, RefreshIcon } from './icons';

interface GeneratedImagesProps {
  images: string[];
  onStartOver: () => void;
}

const GeneratedImages: React.FC<GeneratedImagesProps> = ({ images, onStartOver }) => {
  return (
    <div className="w-full flex flex-col items-center text-center">
      <h2 className="text-3xl font-bold text-slate-100 mb-2">Here Are Your AI Photos!</h2>
      <p className="text-slate-400 mb-8">
        {images.length > 0
          ? `You've got ${images.length} new photo${images.length > 1 ? 's' : ''}! Download your favorites or start over.`
          : 'Generation complete, but some images could not be created. Please try again.'
        }
      </p>
      
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 mb-8 w-full">
        {images.map((src, index) => (
          <div key={index} className="relative aspect-square rounded-lg overflow-hidden group shadow-lg bg-slate-800">
            <img src={src} alt={`Generated by AI ${index + 1}`} className="w-full h-full object-cover" />
            <a
              href={src}
              download={`ai-photo-${index + 1}.png`}
              className="absolute bottom-2 right-2 bg-black/60 text-white rounded-full p-2 opacity-0 group-hover:opacity-100 transition-opacity backdrop-blur-sm"
              title="Download"
            >
              <DownloadIcon className="w-5 h-5" />
            </a>
          </div>
        ))}
      </div>

      <div className="flex flex-col sm:flex-row gap-4">
        <button
          onClick={onStartOver}
          className="flex items-center justify-center gap-2 px-6 py-3 bg-slate-700 text-slate-200 font-semibold rounded-lg shadow-md hover:bg-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-500 focus:ring-opacity-75 transition-colors"
        >
          <RefreshIcon className="w-5 h-5" />
          Start Over
        </button>
      </div>
    </div>
  );
};

export default GeneratedImages;
